#!/usr/bin/env python3
"""
Generate C++ golden vectors for lat/lon ↔ ENU (geo_utils vs generate_fake_gps).

Usage:
    python3 tests/gps/gen_geo_golden.py <output.hpp>
"""

from __future__ import annotations

import importlib.util
import math
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
TOOLS_DIR = REPO_ROOT / "tools"

# Short window: every trajectory at 1 Hz (same as nominal SensorLog fixtures).
GOLDEN_DURATION_S = 12.0
GOLDEN_DT_S = 1.0

TOL_M = 1e-4


def load_generator_module():
    spec = importlib.util.spec_from_file_location(
        "generate_fake_gps", TOOLS_DIR / "generate_fake_gps.py"
    )
    mod = importlib.util.module_from_spec(spec)
    assert spec and spec.loader
    sys.modules[spec.name] = mod
    spec.loader.exec_module(mod)
    return mod


def build_samples(gen) -> list[dict]:
    origin = (gen.ORIGIN_LAT, gen.ORIGIN_LON, gen.ORIGIN_ALT_M)
    samples: list[dict] = []

    for name in sorted(gen.TRAJECTORIES):
        fixes = gen.TRAJECTORIES[name](GOLDEN_DURATION_S, GOLDEN_DT_S)
        for idx, fix in enumerate(fixes):
            east, north, up = gen.latlon_to_enu(
                origin[0],
                origin[1],
                origin[2],
                fix.lat,
                fix.lon,
                fix.alt_m,
            )
            lat2, lon2 = gen.enu_to_latlon(origin[0], origin[1], east, north)
            if (
                abs(lat2 - fix.lat) > TOL_M / 1000.0
                or abs(lon2 - fix.lon) > TOL_M / 1000.0
            ):
                raise RuntimeError(f"round-trip failed for {name} idx={idx}")

            samples.append(
                {
                    "trajectory": name,
                    "index": idx,
                    "lat_deg": fix.lat,
                    "lon_deg": fix.lon,
                    "alt_m": fix.alt_m,
                    "east_m": east,
                    "north_m": north,
                    "up_m": up,
                }
            )
    return samples


def emit_header(path: Path, gen, samples: list[dict]) -> None:
    lines = [
        "// Auto-generated by tests/gps/gen_geo_golden.py — do not edit.",
        "#pragma once",
        "#include <cstddef>",
        "",
        "namespace geo_golden {",
        "",
        "struct Origin {",
        "    double lat_deg;",
        "    double lon_deg;",
        "    double alt_m;",
        "};",
        "",
        "struct Sample {",
        "    const char* trajectory;",
        "    int index;",
        "    double lat_deg;",
        "    double lon_deg;",
        "    double alt_m;",
        "    double east_m;",
        "    double north_m;",
        "    double up_m;",
        "};",
        "",
        f"inline constexpr Origin kOrigin{{{gen.ORIGIN_LAT}, {gen.ORIGIN_LON}, {gen.ORIGIN_ALT_M}}};",
        "",
        "inline constexpr Sample kSamples[] = {",
    ]
    for s in samples:
        lines.append(
            f'    {{"{s["trajectory"]}", {s["index"]}, '
            f'{s["lat_deg"]:.9f}, {s["lon_deg"]:.9f}, {s["alt_m"]:.6f}, '
            f'{s["east_m"]:.6f}, {s["north_m"]:.6f}, {s["up_m"]:.6f}}},'
        )
    lines.extend(
        [
            "};",
            f"inline constexpr std::size_t kSampleCount = {len(samples)};",
            "",
            "}  // namespace geo_golden",
            "",
        ]
    )
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <output.hpp>", file=sys.stderr)
        return 1
    gen = load_generator_module()
    samples = build_samples(gen)
    emit_header(Path(sys.argv[1]), gen, samples)
    print(f"Wrote {len(samples)} golden samples -> {sys.argv[1]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
